### ISSUE TITLE
[RFC] Minimum compatibility

### ISSUE THREAD

**Issue by maxhelias** [doctrine-extensions/symfony-bundle#1]
To start the redesign of the bundle, we need to define the scope of compatibility.

I would like to suggest :

- PHP : 7.1.3
    -  The other are no longer maintained and the security patches will be soon for here, but it does not matter. 
    - This is the same version that Symfony 4.4 support
    - 7.1 support the nullable type (`?string`), `void`, constante visibility, iterable and much more, which will be very interesting
- Symfony 4.3, because it is the version that has been the most modified and compatibility below will be complicated

For those who can not meet these minimums will be able to use the original bundle by being aware that they will need to up their config

WDYT ?

**Comment by maxhelias** [comment]
Also Symfony 4.3, for use the mime component on the `Uploadable` support

Or we can get ahead for up to 4.4 for the new directory : https://github.com/symfony/symfony/blob/master/UPGRADE-4.4.md#httpkernel

**Comment by Pierstoval** [comment]
The current bundle has this:

```json
    "require": {
        "php": ">=5.3.2",
        "symfony/framework-bundle": "~2.7|~3.2|~4.0",
        "gedmo/doctrine-extensions": "^2.3.4"
    },
```

I think it's time to bump way higher, require only PHP 7.2 and Symfony 4.4/5+ :)

**Comment by AkenRoberts** [comment]
I'm sorry for not responding earlier, this got lost in my notifications.

My goal moving forward with Doctrine Extensions is to require only supported versions of dependencies. That would mean PHP 7.2 and Symfony 4.2+ (or 4.3 depending on when a tagged release can happen).

I would love to have a way to keep compatibility with earlier Symfony versions, such as the 3.4 LTS, given how many people prefer and depend on them. That is a secondary goal, though, and something where maybe we'd branch or tag differently while providing secondary support.
